# Generated by Django 3.0.4 on 2020-05-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField(max_length=15)),
                ('username2', models.CharField(max_length=15)),
                ('attach', models.FileField(upload_to='')),
            ],
        ),
    ]
